# .github/workflows/git-sync.yml

on:
  pull_request:
    branches:
      develop
    types:
      - closed
     
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nirav7707/Covid-19-Tracker"
          source_branch: "develop"
          destination_repo: "kkataria/Covid-19-Tracker"
          destination_branch: "develop"
