# .github/workflows/git-sync.yml

on:
  pull_request:
    types:
      - closed
     
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nirav7707/Covid-19-Tracker"
          source_branch: "develop"
          destination_repo: "kkataria3010/Covid-19-Tracker"
          destination_branch: "develop"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
